generic-service:
  nameOverride: hmpps-content-hub-feedback-reports
  productId: 'DPS101' # productId for the product that this belongs too, i.e. DPS001, see README.md for details

  # the IRSA service account name for accessing AWS resources
  serviceAccountName: "prisoner-content-hub"

  replicaCount: 4

  image:
    repository: ghcr.io/ministryofjustice/hmpps-content-hub-feedback-reports
    tag: app_version # override at deployment time
    port: 3000

  ingress:
    enabled: true
    host: app-hostname.local # override per environment
    tlsSecretName: hmpps-content-hub-feedback-reports-cert

  livenessProbe:
    httpGet:
      path: /ping

  readinessProbe:
    httpGet:
      path: /ping

  # Environment variables to load into the deployment
  env:
    NODE_ENV: 'production'
    REDIS_ENABLED: 'true'
    REDIS_TLS_ENABLED: 'true'
    TOKEN_VERIFICATION_ENABLED: 'true'
    AUDIT_SQS_REGION: 'eu-west-2'
    AUDIT_SERVICE_NAME: 'DPS101' # Your audit service name

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    # These secrets are created by terraform.
    hmpps-content-hub-feedback-reports-client-creds:
      CLIENT_CREDS_CLIENT_ID: 'CLIENT_CREDS_CLIENT_ID'
      CLIENT_CREDS_CLIENT_SECRET: 'CLIENT_CREDS_CLIENT_SECRET'
    hmpps-content-hub-feedback-reports-auth-code:
      AUTH_CODE_CLIENT_ID: 'AUTH_CODE_CLIENT_ID'
      AUTH_CODE_CLIENT_SECRET: 'AUTH_CODE_CLIENT_SECRET'    
    hmpps-content-hub-feedback-reports-session-secret:
      SESSION_SECRET: 'SESSION_SECRET'
    frontend-redis:
      REDIS_HOST: 'primary_endpoint_address'
      REDIS_AUTH_TOKEN: 'auth_token'
    hmpps-content-hub-feedback-reports-application-insights:
      APPLICATIONINSIGHTS_CONNECTION_STRING: "APPLICATIONINSIGHTS_CONNECTION_STRING"
    prisoner-feedback-rds:
      FEEDBACK_DATABASE_URL: "rds_instance_address"
      FEEDBACK_DATABASE_USERNAME: "database_username"
      FEEDBACK_DATABASE_PASSWORD: "database_password"
      FEEDBACK_DATABASE_NAME: "database_name"

  allowlist:
    groups:
      - internal

generic-prometheus-alerts:
  targetApplication: hmpps-content-hub-feedback-reports
