---
# Per environment values which override defaults in hmpps-content-hub-feedback-reports/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: content-hub-feedback-reports-preprod.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://content-hub-feedback-reports-preprod.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-preprod.prison.service.justice.gov.uk"
    ENVIRONMENT_NAME: PRE-PRODUCTION
    AUDIT_ENABLED: "false"

generic-prometheus-alerts:
  alertSeverity: hmpps-launchpad-nonprod
