---
# Per environment values which override defaults in hmpps-content-hub-feedback-reports/values.yaml

generic-service:
  ingress:
    host: content-hub-feedback-reports.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://content-hub-feedback-reports.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api.prison.service.justice.gov.uk"
    AUDIT_ENABLED: "false"

generic-prometheus-alerts:
  alertSeverity: hmpps-launchpad
